name = "traffic-rider"
compatibility_date = "2026-03-20"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"
watch_dir = "app"

[env.production]
# Add your production environment variables here in Cloudflare Dashboard
