const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');

const postsDirectory = path.join(process.cwd(), 'data', 'md');
const locales = ['en']; // Add more locales if needed

function getAllPosts() {
  const allData = {};
  
  locales.forEach(locale => {
    const localeDir = path.join(postsDirectory, locale);
    if (!fs.existsSync(localeDir)) return;
    
    const fileNames = fs.readdirSync(localeDir);
    allData[locale] = {};
    
    fileNames.forEach(fileName => {
      if (!fileName.endsWith('.md')) return;
      const slug = fileName.replace(/\.md$/, '');
      const fullPath = path.join(localeDir, fileName);
      const fileContents = fs.readFileSync(fullPath, 'utf8');
      const { data, content } = matter(fileContents);
      
      allData[locale][slug] = {
        data,
        content
      };
    });
  });
  
  return allData;
}

const data = getAllPosts();
const outputPath = path.join(process.cwd(), 'lib', 'data-cache.ts');

const content = `
// This file is auto-generated by scripts/build-data.js
// Do not edit manually.
export const postsData: Record<string, Record<string, { data: Record<string, unknown>, content: string }>> = ${JSON.stringify(data, null, 2)};
`;

fs.writeFileSync(outputPath, content);
console.log('Successfully generated lib/data-cache.ts');
